/* generated by build-brands.py. THE single source of company identity.
   No component may choose its own merchant logo. */
var BRANDS = {
 "Choppies": {
  "id": "choppies",
  "name": "Choppies",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://choppies.co.bw/",
  "cover": "brands/choppies/general_grocery.jpg",
  "coverStatus": "verified_official_asset_url",
  "coverSource": "https://choppies.co.bw/wp-content/uploads/2026/08/Choppies_Product_Display_800x800-1.jpg"
 },
 "Pick n Pay": {
  "id": "picknpay_bw",
  "name": "Pick n Pay Botswana",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://pnpbotswana.co.bw/",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "Spar": {
  "id": "spar_bw",
  "name": "SPAR Botswana",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://spar.co.bw/",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "Sefalana": {
  "id": "sefalana",
  "name": "Sefalana",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://sefalana.com/",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "Checkers": {
  "id": "checkers",
  "name": "Checkers",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://www.checkers.co.za/",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "Woolworths Food": {
  "id": "woolworths_za",
  "name": "Woolworths South Africa",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://www.woolworths.co.za/images/New_Site/Corporate/Education/MTD_Guide_2.pdf",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "KFC": {
  "id": "kfc_bw",
  "name": "KFC Botswana",
  "logo": "brands/kfc_bw/logo.svg",
  "logoStatus": "approved-local",
  "officialSource": "https://www.kfcbotswana.com/",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "Nando's": {
  "id": "nandos_bw",
  "name": "Nando's Botswana",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://www.nandos.co.bw/",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "RocoMamas": {
  "id": "rocomamas_bw",
  "name": "RocoMamas Botswana",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://rocomamas.com/bw",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "Clicks Pharmacy": {
  "id": "clicks_bw",
  "name": "Clicks",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://clicks.co.za/",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "Dis-Chem": {
  "id": "dischem_bw",
  "name": "Dis-Chem",
  "logo": null,
  "logoStatus": "verified_official_brand_source",
  "officialSource": "https://www.dischem.co.za/",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 },
 "Sprint Couriers": {
  "id": "sprint",
  "name": "Sprint Couriers",
  "logo": "brands/sprint/logo-mark.png",
  "logoStatus": "approved-local",
  "officialSource": "approved internal corporate asset",
  "cover": null,
  "coverStatus": "none",
  "coverSource": null
 }
};
var BRAND_POLICY = {
 "realCompanyLogoMode": "approved-only",
 "allowGeneratedRealLogos": false,
 "allowSemanticLogoGuessing": false,
 "allowSearchThumbnailAsLogo": false,
 "allowRandomPhotoAsMerchantLogo": false,
 "unknownMerchantLogoFallback": "text-only",
 "logoObjectFit": "contain",
 "coverObjectFit": "cover",
 "productObjectFit": "cover"
};
var PLACEHOLDERS = {
 "product": "brands/placeholders/photo-unavailable.svg",
 "pharmacy": "brands/placeholders/pharmacy-unverified.svg",
 "grocery": "brands/placeholders/groceries-unverified.svg",
 "restaurant": "brands/placeholders/restaurant-unverified.svg",
 "merchant": "brands/placeholders/merchant-unverified.svg"
};
